project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "works/*.qmd"
  resources:
    - pdfs/**
    - viewer.html

website:
  title: "Kim Bridges — Fiction"
  navbar:
    left:
      - href: index.qmd
        text: Fiction
    right:
      - icon: house
        href: https://kimbridges.info
        text: kimbridges.info
      - icon: globe
        href: https://www.kimbridges.com
        text: kimbridges.com

format:
  html:
    theme: cosmo
    css: custom.css
    toc: false
    code-copy: true
