# pkm_health.R -- PKM health check and maintenance tools
# Built 2026-07-30 (Tier 2). Lives beside the files it scans.
# Run:  source("G:/My Drive/Projects_Index/pkm_health.R"); pkm_health()
#
# NOTE: this file is edited through the RStudio MCP bridge, whose guard
# scans SOURCE TEXT. Do not write the blocked shell-function names with a
# trailing parenthesis anywhere in here, even inside a string or comment.

PKM <- list(
  index  = "G:/My Drive/Projects_Index",
  drive  = "G:/My Drive",
  logs   = "G:/My Drive/Projects_Index/logs",
  venues = data.frame(
    venue  = c("documents", "stories", "fiction", "collections"),
    folder = c("kimbridges-documents", "kimbridges-stories",
               "kimbridges-fiction", "kimbridges-collections"),
    subdir = c("docs", "stories", "works", "."),
    url    = c("https://kimbridges-documents.netlify.app",
               "https://kimbridges-stories.netlify.app",
               "https://kimbridges-fiction.netlify.app",
               "https://kimbridges-collections.netlify.app"),
    stringsAsFactors = FALSE),
  # Size budgets, KB. Split HOT vs REFERENCE on 2026-07-31 (Tier 3): a file
  # read every session and a file read once a month were being judged by the
  # same standard, which made the check cry wolf -- and a check that cries
  # wolf gets ignored. HOT = the session-start reads. PROJECT = read when that
  # project is in focus. REFERENCE = read on demand; generous by design.
  budget = list(
    hot = c("pkm_card.md" = 6, "project_index.md" = 30, "proj_PKM.md" = 25),
    proj = 45, reference = 200, session_log = 250, focus_block = 6),
  scratch_days = 14
)

## ---- small helpers --------------------------------------------------

.kb <- function(paths) round(file.info(paths)$size / 1024, 1)

.read <- function(f) readLines(f, warn = FALSE)

.front_matter <- function(f) {
  a <- .read(f)
  d <- which(trimws(a) == "---")
  if (length(d) < 2 || d[1] != 1) return(NULL)
  y <- tryCatch(yaml::yaml.load(paste(a[(d[1] + 1):(d[2] - 1)], collapse = "\n")),
                error = function(e) NULL)
  y
}

.flat <- function(v) if (is.null(v)) NA_character_ else paste(unlist(v), collapse = "; ")

.probe <- function(url, timeout = 20) {
  h <- curl::new_handle(nobody = TRUE, followlocation = TRUE, timeout = timeout)
  r <- tryCatch(curl::curl_fetch_memory(url, handle = h), error = function(e) NULL)
  if (is.null(r)) NA_integer_ else r$status_code
}

## ---- JOB 1: generate the works register -----------------------------

pkm_works <- function() {
  out <- list()
  for (i in seq_len(nrow(PKM$venues))) {
    v <- PKM$venues[i, ]
    dir <- if (v$subdir == ".") file.path(PKM$drive, v$folder)
           else file.path(PKM$drive, v$folder, v$subdir)
    if (!dir.exists(dir)) next
    qs <- list.files(dir, pattern = "[.]qmd$", full.names = TRUE)
    qs <- qs[basename(qs) != "index.qmd"]
    qs <- qs[!startsWith(basename(qs), "_")]
    for (q in qs) {
      fm   <- .front_matter(q)
      slug <- sub("[.]qmd$", "", basename(q))
      rel  <- if (v$subdir == ".") paste0(slug, ".html")
              else paste0(v$subdir, "/", slug, ".html")
      out[[length(out) + 1]] <- data.frame(
        venue    = v$venue,
        slug     = slug,
        title    = .flat(fm$title),
        subtitle = .flat(fm$subtitle),
        date     = .flat(fm$date),
        categories = .flat(fm$categories),
        pdf      = .flat(fm$pdf),
        source   = q,
        rel      = rel,
        url      = paste0(v$url, "/", rel),
        modified = format(file.info(q)$mtime, "%Y-%m-%d"),
        stringsAsFactors = FALSE)
    }
  }
  w <- do.call(rbind, out)
  w[order(w$venue, w$slug), ]
}

pkm_register <- function(write = TRUE) {
  w <- pkm_works()
  if (!write) return(w)
  n <- table(w$venue)
  L <- c("# Works Register",
         paste0("_Generated by pkm_health.R on ", format(Sys.Date()), ". DO NOT EDIT BY HAND._"),
         "",
         "One row per published work across the four venues. A work is tracked here,",
         "not as a proj_*.md file. A work earns a proj_*.md only when it acquires",
         "DEVELOPMENT -- code, a package, a method, a multi-session build.",
         "",
         paste0("**", nrow(w), " works** -- ",
                paste(paste0(names(n), " ", as.integer(n)), collapse = ", ")),
         "")
  for (v in PKM$venues$venue) {
    s <- w[w$venue == v, ]
    if (!nrow(s)) next
    L <- c(L, paste0("## ", v, " (", nrow(s), ")"), "",
           "| Work | Date | Categories | Live URL |",
           "|---|---|---|---|")
    for (j in seq_len(nrow(s)))
      L <- c(L, paste0("| ", s$title[j], " | ", s$date[j], " | ",
                       s$categories[j], " | ", s$rel[j], " |"))
    L <- c(L, "")
  }
  f <- file.path(PKM$index, "works_register.md")
  writeLines(L, f)
  message("wrote ", f, " -- ", nrow(w), " works")
  invisible(w)
}

## ---- JOB 2: reconcile source -> _site -> live -----------------------

pkm_reconcile <- function(check_live = TRUE) {
  w <- pkm_works()
  w$rendered <- NA; w$live <- NA_integer_
  for (i in seq_len(nrow(w))) {
    v <- PKM$venues[PKM$venues$venue == w$venue[i], ]
    w$rendered[i] <- file.exists(file.path(PKM$drive, v$folder, "_site", w$rel[i]))
    if (check_live) w$live[i] <- .probe(w$url[i])
  }
  w$ok <- w$rendered & (!check_live | (!is.na(w$live) & w$live == 200))
  w
}

pkm_orphans <- function() {
  out <- list()
  for (i in seq_len(nrow(PKM$venues))) {
    v  <- PKM$venues[i, ]
    sub_ <- if (v$subdir == ".") "" else v$subdir
    sd <- file.path(PKM$drive, v$folder, "_site", sub_)
    bd <- file.path(PKM$drive, v$folder, sub_)
    if (!dir.exists(sd)) next
    html <- list.files(sd, pattern = "[.]html$")
    html <- html[html != "index.html"]
    # Quarto renders .md as well as .qmd -- accept either as a source
    q <- file.path(bd, sub("[.]html$", ".qmd", html))
    m <- file.path(bd, sub("[.]html$", ".md",  html))
    miss <- html[!file.exists(q) & !file.exists(m)]
    if (length(miss))
      out[[length(out) + 1]] <- data.frame(venue = v$venue,
        rendered_without_source = miss, stringsAsFactors = FALSE)
  }
  if (!length(out)) return(data.frame())
  do.call(rbind, out)
}

## ---- JOB 3: verify _Log: pointers -----------------------------------

pkm_pointers <- function() {
  pf <- list.files(PKM$index, pattern = "[.]md$", full.names = TRUE)
  ptr <- list(); ref <- character(0)
  for (z in pf) {
    a <- .read(z); h <- a[seq_len(min(15, length(a)))]
    p <- h[startsWith(h, "_Log: ")]
    if (!length(p)) next
    tgt <- sub("_$", "", substring(p[1], 7))
    ref <- c(ref, basename(tgt))
    ptr[[length(ptr) + 1]] <- data.frame(file = basename(z), pointer = tgt,
      resolves = file.exists(file.path(PKM$index, tgt)), stringsAsFactors = FALSE)
  }
  ptr <- if (length(ptr)) do.call(rbind, ptr) else data.frame()
  have <- list.files(PKM$logs, pattern = "[.]md$")
  list(pointers = ptr,
       broken   = if (nrow(ptr)) ptr$file[!ptr$resolves] else character(0),
       orphans  = setdiff(setdiff(have, ref), c("focus_history.md", "session_log_archive.md")))
}

## ---- JOB 4: drift between proj files and their named locations ------

.drop_tail <- function(z) {
  z <- trimws(z)
  while (nchar(z) > 0 &&
         substring(z, nchar(z)) %in% c(",", ";", ".", "(", ")", "/", "-", ":", "*"))
    z <- trimws(substring(z, 1, nchar(z) - 1))
  z
}

.resolve_path <- function(s) {
  s <- .drop_tail(s)
  if (!grepl("/", s, fixed = TRUE)) return(NA_character_)   # prose, not a path
  for (k in seq_len(15)) {
    if (file.exists(s)) return(s)          # dirs AND files both count
    parts <- strsplit(s, " ", fixed = TRUE)[[1]]
    if (length(parts) <= 1) break
    s <- .drop_tail(paste(parts[-length(parts)], collapse = " "))
  }
  NA_character_
}

.extract_paths <- function(line) {
  bs <- rawToChar(as.raw(92))
  ln <- gsub(bs, "/", line, fixed = TRUE)
  out <- character(0)
  for (p in strsplit(ln, "`", fixed = TRUE)[[1]]) {
    k <- regexpr("G:", p, fixed = TRUE)
    if (k > 0) out <- c(out, substring(p, k))
  }
  out
}

# Bounded scan: a full recursive walk of a Projects/ folder over Drive
# Stream hangs the bridge (learned 2026-07-30 -- two 60s timeouts). Depth 2,
# capped, and the big generated folders skipped. This is a DRIFT FLAG, not a
# census; it only needs the newest interesting mtime.
.SKIP_DIRS <- c("_site", "_book", "_output", ".quarto", ".git", "renv",
                "site_libs", "_freeze", ".Rproj.user")

.newest_mtime <- function(d, max_dirs = 40, max_files = 3000) {
  if (!dir.exists(d)) return(file.info(d)$mtime)   # a single named file
  e <- list.files(d, full.names = TRUE)
  isdir <- dir.exists(e)
  subs <- e[isdir]
  subs <- subs[!basename(subs) %in% .SKIP_DIRS]
  all <- e[!isdir]
  for (s in head(subs, max_dirs)) {
    g <- list.files(s, full.names = TRUE)
    g <- g[!basename(g) %in% .SKIP_DIRS]
    all <- c(all, g)
    if (length(all) > max_files) break
  }
  all <- head(all, max_files)
  if (!length(all)) return(as.POSIXct(NA))
  suppressWarnings(max(file.info(all)$mtime, na.rm = TRUE))
}

.status_of <- function(z) {
  h <- readLines(z, n = 10, warn = FALSE)
  s <- h[startsWith(h, "_Status:")]
  if (!length(s)) return(NA_character_)
  v <- trimws(sub("_Status:", "", s[1], fixed = TRUE))
  strsplit(sub("_$", "", v), " ")[[1]][1]
}

# Drift is only meaningful for ACTIVE projects: a Complete project whose
# folder is newer than its proj file is normal, and a Standing venue
# receives work continuously by definition. Scoping to Active cut this from
# over 60s (two bridge timeouts on 2026-07-30) to a couple of seconds.
pkm_drift <- function(min_days = 7, statuses = "Active") {
  skip_roots <- file.path(PKM$drive,
    c(PKM$venues$folder, "kimbridges-info", "Projects_Index"))
  too_broad <- c("G:/My Drive", "G:/My Drive/Projects", "G:/My Drive/Projects_Index")
  pf <- list.files(PKM$index, pattern = "[.]md$", full.names = TRUE)
  pf <- pf[startsWith(basename(pf), "proj_")]
  pf <- pf[vapply(pf, function(z) isTRUE(.status_of(z) %in% statuses), logical(1))]
  out <- list()
  for (z in pf) {
    a <- .read(z)
    s <- which(startsWith(a, "## Locations"))
    if (!length(s)) next
    e <- which(startsWith(a, "## ")); e <- e[e > s[1]]
    blk <- a[s[1]:(if (length(e)) e[1] - 1 else length(a))]
    raws <- unique(unlist(lapply(blk, .extract_paths)))
    seen <- character(0)
    for (rw in raws) {
      if (!grepl("/", rw, fixed = TRUE)) next   # prose, not a path
      d <- .resolve_path(rw)
      if (is.na(d)) {
        out[[length(out) + 1]] <- data.frame(file = basename(z),
          location = substr(rw, 1, 55), issue = "location not found",
          days = NA_real_, stringsAsFactors = FALSE); next
      }
      if (d %in% too_broad || d %in% seen) next
      if (any(startsWith(d, skip_roots))) next
      seen <- c(seen, d)
      newest <- .newest_mtime(d)
      if (!is.finite(newest)) next
      gap <- as.numeric(difftime(newest, file.info(z)$mtime, units = "days"))
      if (gap > min_days)
        out[[length(out) + 1]] <- data.frame(file = basename(z), location = d,
          issue = "code newer than the proj file", days = round(gap, 1),
          stringsAsFactors = FALSE)
    }
  }
  if (!length(out)) return(data.frame())
  o <- do.call(rbind, out)
  o[order(-replace(o$days, is.na(o$days), -1)), ]
}

## ---- JOB 5: size budget (the flow control, added 2026-07-30) --------

pkm_budget <- function() {
  fs <- list.files(PKM$index, pattern = "[.]md$", full.names = TRUE)
  b <- PKM$budget
  cls <- function(n) if (n %in% names(b$hot)) "HOT"
                     else if (n == "session_log.md") "REFERENCE"
                     else if (startsWith(n, "proj_")) "PROJECT" else "REFERENCE"
  lim <- function(n) if (n %in% names(b$hot)) unname(b$hot[n])
                     else if (n == "session_log.md") b$session_log
                     else if (startsWith(n, "proj_")) b$proj else b$reference
  d <- data.frame(file = basename(fs), kb = .kb(fs), stringsAsFactors = FALSE)
  d$class <- vapply(d$file, cls, character(1))
  d$budget_kb <- vapply(d$file, lim, numeric(1))
  d$over <- round(d$kb - d$budget_kb, 1)
  d$splittable <- vapply(fs, function(z) {
    x <- .read(z); any(trimws(x) %in% c("# Log", "## Log", "### Log")) }, logical(1))
  d <- d[d$over > 0, ]
  d[order(-d$over), c("file", "class", "kb", "budget_kb", "over", "splittable")]
}

# Bucket 4 retention (Tier 3): build scratch is regenerable and must not linger.
# Bucket 4 retention. The rule is "delete once the deploy is verified live",
# which no clock can detect -- so report EVERY scratch folder, and mark the ones
# past the threshold. A check that answers "none" while 226 MB sits stranded is
# worse than no check: it certifies a problem as absent. (2026-07-31)
pkm_scratch <- function(days = PKM$scratch_days) {
  root <- "C:/temp"
  if (!dir.exists(root)) return(data.frame())
  d <- list.dirs(root, recursive = FALSE)
  if (!length(d)) return(data.frame())
  age <- as.numeric(difftime(Sys.time(), file.info(d)$mtime, units = "days"))
  mb <- vapply(d, function(z) {
    fs <- list.files(z, recursive = TRUE, full.names = TRUE)
    if (!length(fs)) 0 else round(sum(file.info(fs)$size, na.rm = TRUE) / 1048576) },
    numeric(1))
  out <- data.frame(folder = basename(d), age_days = round(age, 1), MB = mb,
                    past_threshold = age > days, stringsAsFactors = FALSE)
  out[order(-out$MB), ]
}

pkm_focus_size <- function() {
  a <- .read(file.path(PKM$index, "project_index.md"))
  i <- which(startsWith(a, "**Active Focus"))
  if (!length(i)) return(data.frame())
  data.frame(line = i, kb = round(nchar(a[i]) / 1024, 1),
             budget_kb = PKM$budget$focus_block,
             over = round(nchar(a[i]) / 1024 - PKM$budget$focus_block, 1),
             stringsAsFactors = FALSE)
}

## ---- REMEDIES -------------------------------------------------------
# Each one: snapshot first, byte-exact split, verify losslessness, and
# RESTORE FROM THE SNAPSHOT if verification fails. Never run automatically.

.snapshot <- function(paths) {
  arc <- file.path(PKM$drive, paste0("Projects_Index_archive_", format(Sys.Date())))
  dir.create(arc, showWarnings = FALSE)
  ok <- file.copy(paths, file.path(arc, basename(paths)), overwrite = TRUE)
  same <- file.info(paths)$size == file.info(file.path(arc, basename(paths)))$size
  if (!all(ok) || !all(same)) stop("snapshot failed -- aborting before any write")
  file.path(arc, basename(paths))
}

.spanner <- function(r) {
  nl <- which(r == as.raw(10)); N <- length(nl)
  list(N = N, get = function(a, b) {
    s <- if (a == 1) 1L else nl[a - 1] + 1L
    e <- if (b >= N) length(r) else nl[b]
    if (a > b) raw(0) else r[s:e]
  })
}

.verify <- function(orig_file, new_files, skip_head = 3) {
  o <- readLines(orig_file, warn = FALSE)
  n <- unlist(lapply(new_files, function(z) readLines(z, warn = FALSE)))
  body <- o[seq(skip_head + 1, length(o))]
  body <- body[nzchar(trimws(body))]
  setdiff(body, n)
}

split_tail <- function(file, dry_run = TRUE) {
  f <- file.path(PKM$index, file)
  if (!file.exists(f)) stop("no such file: ", file)
  a  <- readLines(f, warn = FALSE)
  li <- which(trimws(a) %in% c("# Log", "## Log", "### Log"))
  if (!length(li)) stop(file, " has no Log heading -- use a different remedy")
  li <- li[1]
  logfn <- sub("[.]md$", "_log.md", file)
  lf    <- file.path(PKM$logs, logfn)
  hf <- which(startsWith(a, "_")); hf <- hf[hf < 15]
  if (!length(hf)) stop("no header field block found in ", file)
  hf <- max(hf)
  has_ptr <- any(startsWith(a, "_Log: "))
  cut <- li - 1
  while (cut > 1 && !nzchar(trimws(a[cut]))) cut <- cut - 1
  if (trimws(a[cut]) == "---") cut <- cut - 1
  n_entries <- sum(startsWith(a[li:length(a)], "### 20"))
  if (dry_run) {
    message(file, ": Log heading at line ", li, ", ", n_entries,
            " dated entries, tail is ",
            round(nchar(paste(a[li:length(a)], collapse = "")) / 1024, 1), " KB")
    message("  -> would ", if (has_ptr) "APPEND to " else "CREATE ", logfn)
    return(invisible(NULL))
  }
  snap <- .snapshot(f)
  r <- readBin(f, "raw", file.info(f)$size); sp <- .spanner(r)
  ptr  <- if (has_ptr) raw(0) else charToRaw(paste0("_Log: logs/", logfn, "\r\n"))
  stub <- charToRaw(paste0("\r\n---\r\n## Log\r\n\r\nThe dated log for this project lives in `logs/",
            logfn, "`. Verbatim and unedited.\r\nNew entries go there, not here. (Split ",
            format(Sys.Date()), " by pkm_health.R)\r\n"))
  head <- c(sp$get(1, hf), ptr, sp$get(hf + 1, cut), stub)
  newtail <- sp$get(li, sp$N)
  if (has_ptr && file.exists(lf)) {
    tail <- c(readBin(lf, "raw", file.info(lf)$size), charToRaw("\r\n"), newtail)
  } else {
    tail <- c(charToRaw(paste0("# ", sub("^proj_", "", sub("[.]md$", "", file)),
      " -- project log\r\n_Split from ", file, " on ", format(Sys.Date()),
      ". Verbatim; nothing edited._\r\n_Live project file: `../", file, "`_\r\n\r\n---\r\n\r\n")),
      newtail)
  }
  writeBin(head, f); writeBin(tail, lf)
  miss <- .verify(snap, c(f, lf))
  if (length(miss)) {
    file.copy(snap, f, overwrite = TRUE)
    stop("VERIFICATION FAILED (", length(miss), " lines unaccounted). Restored from snapshot.")
  }
  message(file, ": ", .kb(snap), " -> ", .kb(f), " KB | ", logfn, " = ", .kb(lf),
          " KB | lossless (", n_entries, " entries moved)")
  invisible(TRUE)
}

archive_focus <- function(new_focus = NULL, dry_run = TRUE) {
  f <- file.path(PKM$index, "project_index.md")
  h <- file.path(PKM$logs, "focus_history.md")
  a <- readLines(f, warn = FALSE)
  i <- which(startsWith(a, "**Active Focus"))
  if (!length(i)) stop("no Active Focus block found")
  i <- i[1]
  if (dry_run) {
    message("Active Focus at line ", i, " is ", round(nchar(a[i]) / 1024, 1),
            " KB -> would move to logs/focus_history.md")
    return(invisible(NULL))
  }
  snap <- .snapshot(c(f, h))
  r <- readBin(f, "raw", file.info(f)$size); sp <- .spanner(r)
  block <- sp$get(i, i)
  repl <- if (is.null(new_focus)) charToRaw(paste0(
      "**Active Focus (", format(Sys.Date()), "): NOT YET SET** -- previous focus archived to ",
      "`logs/focus_history.md`. Confirm or redirect at session start.\r\n"))
    else charToRaw(paste0(new_focus, "\r\n"))
  writeBin(c(sp$get(1, i - 1), repl, sp$get(i + 1, sp$N)), f)
  hr <- readBin(h, "raw", file.info(h)$size)
  mark <- charToRaw("## Superseded Active Focus blocks\r\n\r\n")
  pos <- grepRaw(mark, hr, fixed = TRUE)
  if (!length(pos)) { file.copy(snap, c(f, h), overwrite = TRUE); stop("marker not found; restored") }
  at <- pos[1] + length(mark)
  note <- charToRaw(paste0("<!-- superseded ", format(Sys.Date()), " -->\r\n"))
  writeBin(c(hr[seq_len(at - 1)], note, block, charToRaw("\r\n"), hr[at:length(hr)]), h)
  message("focus block archived: project_index.md now ", .kb(f), " KB")
  invisible(TRUE)
}

split_session_log <- function(keep = 15, dry_run = TRUE) {
  f <- file.path(PKM$index, "session_log.md")
  g <- file.path(PKM$logs, "session_log_archive.md")
  a <- readLines(f, warn = FALSE)
  hd <- which(startsWith(a, "## "))
  if (length(hd) <= keep) { message("only ", length(hd), " entries -- nothing to archive"); return(invisible(NULL)) }
  cutline <- hd[keep + 1]
  if (dry_run) {
    message(length(hd), " entries; keeping ", keep, ", archiving ", length(hd) - keep,
            " from line ", cutline, " (", round(nchar(paste(a[cutline:length(a)], collapse="")) / 1024, 1), " KB)")
    return(invisible(NULL))
  }
  snap <- .snapshot(f)
  r <- readBin(f, "raw", file.info(f)$size); sp <- .spanner(r)
  note <- charToRaw(paste0("\r\n---\r\n\r\nOlder entries (", length(hd) - keep,
    ") were moved to `logs/session_log_archive.md` on ", format(Sys.Date()),
    " by pkm_health.R.\r\nThey are verbatim. Search there before concluding an entry is missing.\r\n"))
  hdr <- charToRaw(paste0("# Session Log -- archive\r\n_Split from session_log.md on ",
    format(Sys.Date()), ". Verbatim; nothing edited._\r\n\r\n---\r\n\r\n"))
  writeBin(c(sp$get(1, cutline - 1), note), f)
  writeBin(c(hdr, sp$get(cutline, sp$N)), g)
  miss <- .verify(snap, c(f, g), skip_head = 0)
  if (length(miss)) { file.copy(snap, f, overwrite = TRUE)
    stop("VERIFICATION FAILED (", length(miss), " lines). Restored from snapshot.") }
  message("session_log.md: ", .kb(snap), " -> ", .kb(f), " KB | archive = ", .kb(g), " KB | lossless")
  invisible(TRUE)
}


## ---- JOB 6: consolidation tracking (added 2026-07-30) ---------------
# Target state (Kim, 2026-07-30):
#   * every venue site has a GitHub repo holding its SOURCE (source-only,
#     lean repos -- binaries stay on Drive and Netlify)
#   * legacy platforms (Quarto Pub, hflip, Exposure) are FROZEN, not deleted:
#     old links keep working, no new work goes there
# The useful metric is therefore not a deletion count. It is (a) how many
# venues still lack a repo, and (b) which legacy pages have no equivalent on
# a kimbridges venue -- those are the ones actually exposed if a platform
# ever disappears.

VENUE_GITIGNORE <- c("_site/", "_book/", ".quarto/", "site_libs/", "_freeze/",
  "pdfs/", "images/", "*.pdf", "*.jpg", "*.jpeg", "*.png", "*.tif", "*.mp3",
  "*.mp4", ".Rproj.user/", ".Rhistory", ".RData")

.git_remote <- function(d) {
  cf <- file.path(d, ".git", "config")
  if (!file.exists(cf)) return(NA_character_)
  a <- readLines(cf, warn = FALSE)
  u <- a[grepl("url = ", a, fixed = TRUE)]
  if (!length(u)) return(NA_character_)
  trimws(sub("url = ", "", u[1], fixed = TRUE))
}

.gh_repos <- function() {
  r <- tryCatch(jsonlite::fromJSON(
    "https://api.github.com/users/kimbridges/repos?per_page=100"),
    error = function(e) NULL)
  if (is.null(r)) character(0) else sort(r$name)
}

pkm_consolidation <- function(check_legacy = TRUE) {
  repos <- .gh_repos()
  vf <- c(PKM$venues$folder, "kimbridges-info")
  ven <- data.frame(site = vf,
    has_git = dir.exists(file.path(PKM$drive, vf, ".git")),
    remote  = vapply(file.path(PKM$drive, vf), .git_remote, character(1)),
    gitignore = file.exists(file.path(PKM$drive, vf, ".gitignore")),
    stringsAsFactors = FALSE)
  pd <- list.dirs(file.path(PKM$drive, "Projects"), recursive = FALSE)
  prj <- data.frame(project = basename(pd),
    local_clone = dir.exists(file.path(pd, ".git")),
    public_repo = basename(pd) %in% repos,
    stringsAsFactors = FALSE)
  prj$issue <- ifelse(prj$local_clone & !prj$public_repo, "clone but no public repo",
               ifelse(!prj$local_clone & prj$public_repo, "public repo but no local clone", ""))
  leg <- data.frame()
  if (check_legacy) {
    a <- .read(file.path(PKM$index, "inventory_all_projects.md"))
    grab <- function(pat) {
      out <- character(0)
      for (ln in a) {
        k <- regexpr(pat, ln, fixed = TRUE)
        if (k > 0) {
          s <- strsplit(substring(ln, k), "[ )>,]")[[1]][1]
          if (nchar(s) > nchar(pat) + 2) out <- c(out, sub("[.,]$", "", s))
        }
      }
      unique(out)
    }
    for (pl in c("https://kim.quarto.pub", "hflip.co", "exposure.co",
                 "soundcloud.com", "issuu.com/kimbridges")) {
      u <- grab(pl)
      if (length(u)) leg <- rbind(leg, data.frame(platform = pl, url = u,
                                                  stringsAsFactors = FALSE))
    }
  }
  list(venues = ven, projects = prj[prj$issue != "", ], legacy = leg,
       repos = repos,
       venues_without_repo = sum(!ven$has_git),
       legacy_pages = nrow(leg))
}


## ---- JOB 7: legacy gap -- the PRE-DELETION GATE ---------------------
# Kim will retire Quarto Pub / hflip / Exposure by DELETING THE ACCOUNTS,
# not item by item (per-item deletion is impractical; Quarto Pub blocks it).
# That is a ONE-WAY DOOR: every page goes at once and its links break. So the
# gate before deleting an account is: does every page on it have an
# equivalent on a kimbridges venue?
#
# MATCHING LESSON (2026-07-30): match on the PDF FILENAME first. Legacy slugs
# name the PDF (hflip.co/merritt_island.html) while venue slugs name the story
# (wading-birds-of-black-point-wildlife-drive). Slug-to-slug matching reported
# 22 orphans; PDF-first matching reduced it to 2. Do not trust a token score
# alone -- it is a triage aid, not a verdict.
.LSTOP <- c("the","of","in","and","a","at","on","to","for","my","an","is","part")
.ltok <- function(s) { s <- tolower(s)
  for (ch in c("-","_",".","/","'",":",",")) s <- gsub(ch, " ", s, fixed = TRUE)
  t <- strsplit(trimws(s), " +")[[1]]; unique(t[nchar(t) > 2 & !t %in% .LSTOP]) }
.lnorm <- function(s) { s <- tolower(s)
  for (ch in c("-","_",".","/"," ","'")) s <- gsub(ch, "", s, fixed = TRUE); s }
.lscore <- function(A, B) { if (!length(A) || !length(B)) return(0)
  round(sum(vapply(A, function(x) any(x == B |
    (nchar(x) >= 4 & substr(B, 1, 4) == substr(x, 1, 4))), logical(1))) /
    min(length(A), length(B)), 2) }

pkm_legacy_gap <- function() {
  w <- pkm_works()
  nested <- list.files(file.path(PKM$drive, "kimbridges-collections"),
                       pattern = "[.]qmd$", recursive = TRUE)
  nested <- nested[grepl("/", nested, fixed = TRUE)]
  key <- rbind(data.frame(slug = w$slug, title = w$title, pdf = w$pdf,
                          stringsAsFactors = FALSE),
               data.frame(slug = sub("[.]qmd$", "", basename(nested)),
                          title = sub("[.]qmd$", "", basename(nested)),
                          pdf = NA_character_, stringsAsFactors = FALSE))
  key$pdfbase <- ifelse(is.na(key$pdf), NA_character_,
                        sub("[.]pdf$", "", basename(key$pdf)))
  leg <- pkm_consolidation()$legacy
  leg$slug <- vapply(leg$url, function(u) {
    p <- strsplit(sub("/$", "", u), "/", fixed = TRUE)[[1]]
    sub("[.]html$", "", p[length(p)]) }, character(1))
  leg <- leg[nchar(leg$slug) > 2 & !leg$slug %in% c("hflip", "hflip:"), ]
  nk <- .lnorm(key$slug); nt <- .lnorm(key$title)
  np <- .lnorm(ifelse(is.na(key$pdfbase), "~~", key$pdfbase))
  kt <- lapply(seq_len(nrow(key)), function(i) unique(c(.ltok(key$slug[i]),
         .ltok(key$title[i]), if (!is.na(key$pdfbase[i])) .ltok(key$pdfbase[i]))))
  r <- t(vapply(leg$slug, function(s) {
    ns <- .lnorm(s)
    j <- which(np == ns); if (length(j)) return(c(key$slug[j[1]], "1", "pdf-exact"))
    j <- which(nk == ns | nt == ns); if (length(j)) return(c(key$slug[j[1]], "1", "slug-exact"))
    v <- vapply(kt, function(B) .lscore(.ltok(s), B), numeric(1)); j <- which.max(v)
    c(key$slug[j], as.character(v[j]), "token") }, character(3)))
  leg$match <- r[, 1]; leg$score <- as.numeric(r[, 2]); leg$how <- r[, 3]
  # WEAK-EVIDENCE GUARD, added 2026-08-01 after a FALSE ALL-CLEAR.
  # `ai-podcasts` matched the Gallery Catalog `Podcast` page at score 1.0 and was
  # reported as "matched", so the gate said 0 hard gaps for Quarto Pub. After the
  # tokeniser drops words under 3 characters, "ai-podcasts" is a SINGLE token; one
  # token matching one token on a 4-character prefix always scores 1.0. A perfect
  # score on one token is not evidence. Such matches are now REVIEW, never matched.
  ntok <- vapply(leg$slug,  function(s) length(.ltok(s)), integer(1))
  mtok <- vapply(leg$match, function(s) length(.ltok(s)), integer(1))
  leg$evidence <- ifelse(leg$how != "token", "exact",
                  ifelse(pmin(ntok, mtok) < 2, "WEAK - one token only", "tokens"))
  leg$verdict <- ifelse(leg$score >= 0.66, "matched",
                 ifelse(leg$score >= 0.34, "possible", "NONE"))
  leg$verdict[leg$evidence == "WEAK - one token only" & leg$verdict == "matched"] <- "REVIEW"
  leg[order(leg$score, leg$platform), c("platform","slug","match","score","how","evidence","verdict")]
}

## ---- DRIVER ---------------------------------------------------------

pkm_health <- function(check_live = TRUE, write_report = TRUE) {
  t0 <- proc.time()[3]
  reg <- pkm_register(write = TRUE)
  rec <- pkm_reconcile(check_live = check_live)
  orp <- pkm_orphans(); ptr <- pkm_pointers()
  dft <- pkm_drift();   bud <- pkm_budget(); foc <- pkm_focus_size()
  cn <- pkm_consolidation()
  scr <- pkm_scratch()
  bad <- rec[!rec$ok, , drop = FALSE]
  L <- c("# PKM Health Report",
    paste0("_Generated ", format(Sys.time(), "%Y-%m-%d %H:%M"),
           " by pkm_health.R. Regenerate; do not edit._"), "",
    "## Summary", "",
    paste0("- **Works registered:** ", nrow(reg)),
    paste0("- **Works failing reconciliation:** ", nrow(bad),
           if (check_live) " (source -> _site -> live)" else " (source -> _site only)"),
    paste0("- **Rendered pages with no source:** ", nrow(orp)),
    paste0("- **Broken _Log: pointers:** ", length(ptr$broken),
           "  |  **orphaned log files:** ", length(ptr$orphans)),
    paste0("- **Projects drifting from their code:** ", nrow(dft)),
    paste0("- **Files over size budget:** ", nrow(bud)),
    paste0("- **Active Focus block:** ", if (nrow(foc)) paste0(foc$kb[1], " KB (budget ", foc$budget_kb[1], ")") else "not found"),
    paste0("- **Venues without a source repo:** ", cn$venues_without_repo, " of ", nrow(cn$venues)),
    paste0("- **Repo/clone mismatches:** ", nrow(cn$projects)),
    paste0("- **Legacy pages awaiting account deletion:** ", cn$legacy_pages),
    paste0("- **Build scratch in C:/temp:** ", nrow(scr), " folder(s), ",
           if (nrow(scr)) sum(scr$MB) else 0, " MB"), "")
  sect <- function(title, d, cols = NULL) {
    if (is.null(d) || !nrow(d)) return(c(paste0("## ", title), "", "None.", ""))
    if (!is.null(cols)) d <- d[, cols, drop = FALSE]
    c(paste0("## ", title), "",
      paste0("| ", paste(names(d), collapse = " | "), " |"),
      paste0("|", paste(rep("---", ncol(d)), collapse = "|"), "|"),
      apply(d, 1, function(r) paste0("| ", paste(r, collapse = " | "), " |")), "")
  }
  L <- c(L,
    sect("Reconciliation failures", bad, c("venue", "slug", "rendered", "live")),
    sect("Rendered without source", orp),
    sect("Drift", dft),
    sect("Over budget", bud),
    sect("Active Focus size", foc),
    sect("Venues without a source repo", cn$venues[!cn$venues$has_git, c("site","has_git","gitignore")]),
    sect("Repo / clone mismatches", cn$projects),
    sect("Build scratch (bucket 4) -- delete once the deploy is verified live", scr),
    sect("Legacy pages by platform", as.data.frame(table(platform = cn$legacy$platform))),
    sect("PRE-DELETION GATE -- legacy pages with no venue equivalent", pkm_legacy_gap()[pkm_legacy_gap()$verdict == "NONE", c("platform","slug","match","score")]))
  if (length(ptr$orphans))
    L <- c(L, "## Orphaned log files", "", paste0("- ", ptr$orphans), "")
  L <- c(L, "---", paste0("_Ran in ", round(proc.time()[3] - t0, 1), " s._"))
  if (write_report) {
    p <- file.path(PKM$index, "pkm_health_report.md")
    writeLines(L, p)
    cat("wrote", p, "\n")
  }
  invisible(list(register = reg, reconcile = rec, orphans = orp,
                 pointers = ptr, drift = dft, budget = bud, focus = foc,
                 consolidation = cn))
}


## ---- JOB 7b: legacy links seen LIVE in the venues -------------------
# WHY THIS EXISTS. pkm_legacy_gap() reads inventory_all_projects.md, so it
# can only protect platforms the INVENTORY records. Eleven SoundCloud embeds
# sat inside published venue pages for months and the gate never saw one of
# them, because no inventory row mentioned SoundCloud (2026-08-02). This
# function goes to ground truth instead: it reads the venue files themselves.
# Run BOTH. Disagreement between them is the finding.
pkm_legacy_live <- function(platforms = c("quarto[. ]pub\\b", "hflip", "exposure\\.co",
                                          "soundcloud", "issuu\\.com"),
                            sources = TRUE) {
  vf  <- c(PKM$venues$folder, "kimbridges-info")
  out <- data.frame()
  for (v in vf) {
    root <- file.path(PKM$drive, v)
    if (!dir.exists(root)) next
    f <- list.files(root, pattern = "[.](qmd|md|html)$", recursive = TRUE,
                    full.names = TRUE)
    # SOURCE only by default: rendered output just mirrors it, at 10x the files
    if (sources) f <- f[!grepl("/_site/|/_output/|/_book/|/site_libs/", f)]
    f <- f[!grepl("/_backup", f)]
    for (pth in f) {
      a <- readLines(pth, warn = FALSE)
      for (pl in platforms) {
        k <- grep(pl, a, ignore.case = TRUE)
        for (j in k) {
          u <- regmatches(a[j], gregexpr("https?://[^ )\"'<]+", a[j]))[[1]]
          u <- u[grepl(pl, u, ignore.case = TRUE)]
          out <- rbind(out, data.frame(venue = v, platform = pl,
                 file = sub(paste0(PKM$drive, "/"), "", pth, fixed = TRUE),
                 line = j, url = if (length(u)) paste(u, collapse = " ") else "",
                 stringsAsFactors = FALSE))
        }
      }
    }
  }
  if (!nrow(out)) return(out)
  # a link with no URL on the line is prose mentioning the platform, not a pointer
  out$kind <- ifelse(out$url == "", "mention only", "LINK")
  out[order(out$platform, out$venue, out$file, out$line), ]
}


## ---- SOURCE MIRROR: hand-authored source only, off Drive ---------------
# Revised 2026-08-03 after measuring. Kim: "We should not be storing derived
# output. That simply wastes space and is not the intent of this backup."
#
# The first cut used VENUE_GITIGNORE -- a BLACKLIST -- and it could not keep up:
# it missed `_output/` (the output-dir every book project uses), so 7 rendered
# Gallery Catalog pages would have been committed. It also admitted 2018 files of
# Jones research data and 278 rendered pages from the documents venue.
# A blacklist has to anticipate every kind of junk. A WHITELIST only has to know
# what source looks like, and that list barely changes.

VENUE_MIRROR <- "C:/repos/kimbridges-venues"

# Hand-authored code and markup. NOT .txt/.csv/.json/.docx -- those are DATA.
SOURCE_EXT <- c("qmd", "rmd", "r", "yml", "yaml", "css", "scss",
                "bib", "py", "js", "md",
                # DATA extensions added 2026-08-18 on Kim's decision (Finding 034).
                # The mirror had never carried a single csv: 82 of 85 files in
                # Projects/Smart_Car were outside the backup while it reported success.
                # Kim: "these files are where data live and that's often our focus".
                # Cost measured before the change: 182 files / 1.8 MB across all projects.
                "csv", "xlsx")

# Hand-authored .html helpers. `html` is NOT in SOURCE_EXT: a first pass admitted
# 12.5 MB of rendered output living outside any _site/_output folder -- R Notebook
# renders, htmlwidget maps, loose Quarto pages. Allowlist by name instead.
SOURCE_FILES <- c("viewer.html")

# Build products and tool state. Anything under these never enters the mirror.
DERIVED_DIRS <- c("_site", "_book", "_output", "_freeze", ".quarto",
                  "site_libs", ".Rproj.user", ".git", "libs")

# Venues holding COPIED-IN rendered documents rather than their own source.
# kimbridges-documents: every top-level folder except docs/ is a rendered document
# whose real source lives in Projects/<name>. Stated as a rule, not a list, so it
# stays true as documents are added.
VENUE_SOURCE_ROOTS <- list("kimbridges-documents" = c(".", "docs"))

.is_source <- function(rel) {
  seg <- strsplit(rel, "/", fixed = TRUE)
  bad <- vapply(seg, function(s) any(s %in% DERIVED_DIRS) ||
                                 any(startsWith(s, "_backup")), logical(1))
  bad <- bad | grepl("\\.~lock\\.", rel, fixed = FALSE)
  # Office lock/owner files. LibreOffice writes .~lock.NAME# ; Excel writes ~$NAME.
  # Added 2026-08-18: allowing xlsx into SOURCE_EXT immediately pulled in a ~$ owner file,
  # which is LOCKED, so it reports a size at source and copies as 0 bytes -- tripping the
  # size-mismatch guard and aborting the whole backup before the commit. Not data; exclude.
  bad <- bad | startsWith(basename(rel), "~$")   # LibreOffice lock files
  ext <- tolower(sub(".*\\.", "", basename(rel)))
  !bad & (ext %in% SOURCE_EXT | basename(rel) %in% SOURCE_FILES)
}

# List the hand-authored source of one folder. Names first, filter BEFORE any
# stat call -- stat-ing every file across Drive Stream venues stalled the bridge.
.src_files <- function(dir, roots = NULL) {
  f <- list.files(dir, recursive = TRUE, all.files = TRUE, no.. = TRUE)
  if (!length(f)) return(character(0))
  if (!is.null(roots)) {
    top <- ifelse(grepl("/", f), sub("/.*", "", f), ".")
    f <- f[top %in% roots]
  }
  sort(f[.is_source(f)])
}

# Refresh one folder's mirror. Returns a summary; does NOT commit.
pkm_mirror <- function(name, from, into = VENUE_MIRROR, roots = NULL) {
  src <- from
  dst <- file.path(into, name)
  if (!dir.exists(src)) stop("no such folder: ", src)
  keep <- .src_files(src, roots)
  dir.create(dst, recursive = TRUE, showWarnings = FALSE)
  for (d in unique(dirname(keep))) if (d != ".")
    dir.create(file.path(dst, d), recursive = TRUE, showWarnings = FALSE)
  copied <- if (length(keep))
    file.copy(file.path(src, keep), file.path(dst, keep),
              overwrite = TRUE, copy.date = TRUE) else logical(0)
  cur  <- list.files(dst, recursive = TRUE, all.files = TRUE, no.. = TRUE)
  cur  <- cur[!startsWith(cur, ".git/")]
  # tolower BOTH sides -- Finding 021: a case-only rename is one file on Windows
  orph <- cur[!(tolower(cur) %in% tolower(keep))]
  if (length(orph)) file.remove(file.path(dst, orph))
  a <- file.info(file.path(src, keep))$size
  b <- file.info(file.path(dst, keep))$size
  list(name = name, tracked = length(keep), copied = sum(copied),
       orphans_removed = length(orph), size_mismatch = sum(a != b, na.rm = TRUE),
       kb = round(sum(b, na.rm = TRUE) / 1024, 1))
}

pkm_mirror_venue <- function(venue, into = VENUE_MIRROR, drive = PKM$drive)
  pkm_mirror(file.path("venues", venue), file.path(drive, venue), into,
             roots = VENUE_SOURCE_ROOTS[[venue]])

pkm_mirror_project <- function(project, into = VENUE_MIRROR, drive = PKM$drive)
  pkm_mirror(file.path("projects", project), file.path(drive, "Projects", project), into)


## ---- SECRET SCAN: run BEFORE any commit ------------------------------
# Added 2026-08-03. GitHub push protection refused the first full mirror push:
# an Anthropic key sat in Projects/LLM_API_R/Claude_API.qmd, commented out with
# ## (which protects nothing). It was never published -- the file is not a chapter
# of the rendered r_api book -- but it would have gone to a PUBLIC repo.
# GitHub caught it. This exists so we catch it first.

SECRET_PATTERNS <- c(
  anthropic  = "sk-ant-[A-Za-z0-9_-]{20,}",
  openai     = "sk-[A-Za-z0-9]{32,}",
  google     = "AIza[0-9A-Za-z_-]{35}",
  github_pat = "gh[pousr]_[A-Za-z0-9]{36}",
  github_fg  = "github_pat_[A-Za-z0-9_]{22,}",
  aws        = "AKIA[0-9A-Z]{16}",
  slack      = "xox[baprs]-[0-9A-Za-z-]{10,}",
  privatekey = "-----BEGIN [A-Z ]*PRIVATE KEY-----"
)

# Scan a folder for credential patterns. Returns file/line/kind -- never the
# secret itself, so the report can be pasted anywhere safely.
pkm_secret_scan <- function(dir = VENUE_MIRROR, patterns = SECRET_PATTERNS,
                            ext = SOURCE_EXT) {
  # EXTENSION FILTER FIRST. Without it, pointing this at Projects/ reads every
  # PDF and image over Drive Stream and hangs the bridge for minutes (done twice
  # on 2026-08-03). A secret lives in text; never open a binary looking for one.
  f <- list.files(dir, recursive = TRUE, full.names = TRUE)
  f <- f[tolower(sub(".*\\.", "", basename(f))) %in% c(tolower(ext), "renviron", "txt")]
  f <- f[!grepl("/[.]git/", f)]
  out <- list()
  for (p in f) {
    a <- tryCatch(readLines(p, warn = FALSE), error = function(e) character(0))
    if (!length(a)) next
    for (nm in names(patterns)) {
      k <- grep(patterns[[nm]], a)
      if (length(k)) out[[length(out) + 1]] <- data.frame(
        file = sub(paste0(dir, "/"), "", p, fixed = TRUE),
        line = k, kind = nm, stringsAsFactors = FALSE)
    }
  }
  if (!length(out)) return(data.frame(file = character(0), line = integer(0),
                                      kind = character(0)))
  do.call(rbind, out)
}


## ---- pkm_backup(): retake the photocopy --------------------------------
# The mirror is a point-in-time snapshot. It does not update itself, so every
# edit on Drive makes the GitHub copy one edit staler. A stale backup is worse
# than an obvious absence: it reads as safety right up to the moment it fails.
# Adopted 2026-08-03 as part of Mechanism 5, so it fires on the same trigger as
# the rest of session close rather than on anyone remembering.

pkm_backup <- function(push = TRUE, message = NULL, quiet = FALSE) {
  say <- function(...) if (!quiet) cat(...)
  m <- VENUE_MIRROR
  if (!dir.exists(file.path(m, ".git"))) stop("no repo at ", m)

  say("refreshing mirror...\n")
  ven <- c(PKM$venues$folder, "kimbridges-info")
  prj <- setdiff(list.dirs(file.path(PKM$drive, "Projects"), recursive = FALSE,
                           full.names = FALSE), grep("^_", list.dirs(
    file.path(PKM$drive, "Projects"), recursive = FALSE, full.names = FALSE),
    value = TRUE))
  rv <- lapply(ven, function(v) pkm_mirror_venue(v))
  rp <- lapply(prj, function(v) pkm_mirror_project(v))
  rk <- pkm_mirror("pkm", PKM$index)
  n  <- sum(vapply(c(rv, rp, list(rk)), function(x) x$tracked, numeric(1)))
  pr <- sum(vapply(c(rv, rp, list(rk)), function(x) x$orphans_removed, numeric(1)))
  mm <- sum(vapply(c(rv, rp, list(rk)), function(x) x$size_mismatch, numeric(1)))
  say("  ", n, " files | ", pr, " pruned | ", mm, " size mismatches\n", sep = "")
  if (mm > 0) stop("size mismatch after copy -- investigate before committing")

  # HARD GATE. Never rely on GitHub to catch a secret: a private repo, or a
  # pattern GitHub does not know, passes silently. Finding 027.
  s <- pkm_secret_scan(m)
  if (nrow(s)) { print(s); stop("SECRETS FOUND -- nothing committed") }
  say("  secret scan: clean\n")

  st <- gert::git_status(repo = m)
  if (!nrow(st)) { say("no changes since last backup\n"); return(invisible(
    list(files = n, changed = 0, pushed = FALSE, head = gert::git_log(repo = m)$commit[1]))) }
  gert::git_add(c("venues", "projects", "pkm", "README.md", ".gitignore"), repo = m)
  msg <- if (is.null(message))
    paste0("Backup refresh: ", nrow(st), " changed of ", n, " tracked") else message
  sig <- gert::git_signature("Kim Bridges", "kim.bridges@gmail.com")
  cid <- gert::git_commit(msg, repo = m, author = sig, committer = sig)
  say("  committed ", substr(cid, 1, 10), " (", nrow(st), " changed)\n", sep = "")

  if (!push) return(invisible(list(files = n, changed = nrow(st), pushed = FALSE, head = cid)))
  credentials::set_github_pat(Sys.getenv("GITHUB_TOKEN"))
  invisible(utils::capture.output(
    gert::git_push(remote = "origin", repo = m, verbose = TRUE), type = "message"))
  # Verify against the SERVER, not the return value. git_push reports success
  # while transferring nothing (Finding 028). git_remote_ls asks the server;
  # GitHub's REST ref endpoint can lag a second behind a push.
  rl <- gert::git_remote_ls("origin", repo = m)
  ok <- identical(cid, rl$oid[rl$ref == "refs/heads/main"])
  say("  push verified against server: ", ok, "\n", sep = "")
  if (!ok) warning("push did NOT reach the server -- check verbose output")
  invisible(list(files = n, changed = nrow(st), pushed = ok, head = cid))
}
