---
title: "Fuel_Analysis"
author: "K. W. Bridges"
date: '2022-05-14'
output: html_document
---

```{r setup, include=FALSE}
## Set some useful chunk options
knitr::opts_chunk$set(echo    = FALSE)  ## FALSE suppresses the listing of the code
knitr::opts_chunk$set(message = FALSE)  ## FALSE suppresses the listing of the message
knitr::opts_chunk$set(warning = FALSE)  ## FALSE suppresses the listing of the warning
knitr::opts_chunk$set(fig.width = 8)
knitr::opts_chunk$set(fig.height = 10)

library(exifr)       ## Read EXIF data from photos
library(flextable)   ## Great table generator
library(gt)          ## Perhaps a more useful table generator
library(dplyr)       ## Data wrangling
library(tidyr)       ## More data wrangling
library(readr)       ## Read files
library(here)        ## Directory assistance and simplification
library(lubridate)   ## Decode and manipulate dates
library(jpeg)        ## Handle jpeg images
library(magick)      ## Manipulate images
library(ggmap)       ## Wrapper for google maps API
library(patchwork)   ## Assemble and annotate output objects
library(ggplot2)     ## Basic plotting
library(cowplot)     ## ggdraw
library(png)         ## Read PNG files
library(ggrepel)     ## Automatic adjustment of labels
library(sp)          ## Used to calculate the center of a set of points
library(raster)      ## Used to calculate the center of a set of points
library(grobblR)     ## To composite the photos on one page; also convert png to grob
library(numbers)     ## mod function
library(pdftools)    ## Build PDF docs
library(tibble)      ## Used for the add_column function
library(webshot)     ## Needed to help save images
library(ptinpoly)    ## Points inside or outside a polygon
library(googlesheets4) ## Read Google Sheets
##library(googledrive)   ## Also used to read Google Sheets
library(BiocManager)
##BiocManager::install("EBImage")
library(EBImage)

## Initialize Google Map key; the is stored in a Project directory.
My_Key <- read_file("P://Hot/Workflow/Workflow/keys/Google_Maps_API_Key.txt")

## Register the Google Maps API Key.
register_google(key = My_Key, account_type = "standard")


```

## Some Map Defaults


```{r defaults}

## Label Defaults
## Note: "lines" is a unit of measure for some dimensions (default)
label_default       <- NULL          ## Needed to get started
label_default$size  <- 4             ## text size        
label_default$color <- "black"       ## text color
label_default$alpha <- 0.9           ## transparency
label_default$label.r <- unit(0.3, "lines") ## rounded corner radius 
label_default$label.size    <- 0.5   ## label border size (mm)
label_default$fill    <- "white"     ## label background color
#label_default$box_padding <- 0.8     ## from point location
#label_default$point.padding <- 0     ## space around point
label_default$segment.color <- "red" ## line from point to label
label_default$segment.size  <- 1
label_default$seed          <- 1002  ## randomizes without a value 

## Point Defaults
point_default <- NULL                ## Needed to get started
point_default$size   <- 3            ## symbols size
point_default$color  <- "black"      ## outside border
point_default$alpha  <- 0.9          ## point transparency
point_default$fill   <- "red"        ## inside color
point_default$shape  <- "circle"     ## circle (symbol 21)
point_default$stroke <- 1            ## border thickness

## Text default
text_default          <- NULL       ## Needed to get started
text_default$size     <- 4          ## text size
text_default$color    <- "black"    ## text color
text_default$fontface <- "plain"    ## alt: italics, bold
text_default$angle    <- 0          ## negative is clockwise

## Google Maps style defaults
## Use these to hide map layers
no_poi        <- "feature:poi|element:labels|visibility:off"
no_transit    <- "feature:transit|element:labels|visibility:off"
no_water      <- "feature:water|element:labels|visibility:off"
no_road       <- "feature:road|element:labels|visibility:off"
no_landscape  <- "feature:landscape|element:labels|visibility:off"
no_administrative <- "feature:administrative|element:labels|visibility:off"
no_country    <- "feature:administrative.country|element:labels|visibility:off"
hide_all      <- "feature:all|element:labels|visibility:off"

```


## Functions

```{r functions}

##### FUNCTION LINEWRAPPER #######################################

LineWrapper <- function(x,length=25){
  
## Wraps text with a default of 25 characters
  
## Handle the column that needs to be wrapped
LineWrapper = sapply(lapply(x, strwrap, width=length), paste, collapse=" \n")  
  
} ## end function Linewrapper

##### FUNCTION tmt_text ##########################################

tmt_text <- function(text,texts_default=text_default){
  
  ## Add labels to a map (used inside ggmap)

  ## Fill in any missing columns with default values 
  ## Thanks to Chris Umphlett on StackOverflow (5/3/2019)
  text <- text %>% 
  add_column(!!!texts_default[!names(texts_default) %in% names(.)])
  
  text$text <- str_replace(text$text,"%%","\n")

  ## Generate the labels
  geom_text(data = text,
            aes(x = lon, y = lat, 
                label = text),
                size          = text$size, 
                color         = text$color, 
                fontface      = text$fontface,
                angle         = text$angle) 

  } ## End function tmt_text

##### FUNCTION tmt_points ########################################

tmt_points <- function(points, points_default=point_default){
  
  ## Add points to a map (used inside ggmap)

  ## Fill in any missing columns with default values 
  ## Thanks to Chris Umphlett on StackOverflow (5/3/2019)
  points <- points %>% 
  add_column(!!!points_default[!names(points_default) %in% names(.)])

  ## Note the following convention for symbol shapes.
  ## You can use circle, square, diamond, triangle,& wedge.
  ## These are mapped to pch 21-25.
  
  points$shape <- sub("circle",  "21",points$shape)
  points$shape <- sub("square",  "22",points$shape)
  points$shape <- sub("diamond", "23",points$shape)
  points$shape <- sub("triangle","24",points$shape)
  points$shape <- sub("wedge",   "25",points$shape)
  
  points$shape <- as.numeric(points$shape)

  ## Generate the labels
  geom_point(data = points,
             aes(x = lon, y = lat),
                  size          = points$size, 
                  color         = points$color,              
                  alpha         = points$alpha,                 
                  fill          = points$fill,
                  shape         = points$shape,
                  stroke        = points$stroke)
  
} ## End Function tmt_points

##### FUNCTION tmt_labels #######################################

tmt_labels <- function(labels,labels_default=label_default){
  
  ## Add labels to a map (used inside ggmap)

  ## Fill in any missing columns with default values 
  ## Thanks to Chris Umphlett on StackOverflow (5/3/2019)
  labels <- labels %>% 
  add_column(!!!labels_default[!names(labels_default) %in% names(.)])

  ## Generate the labels
  geom_label_repel(data = labels,
             aes(x = lon, y = lat, 
                 label = text),
                  size          = labels$size, 
                  color         = labels$color,              
                  alpha         = labels$alpha,                 
                  label.r       = labels$label.r,
                  label.size    = labels$label.size,
                  fill          = labels$fill,
                  box.padding   = 0.8,
                  #point.padding = labels$point.padding,
                  segment.color = labels$segment.color,
                  segment.size  = labels$segment.size,
                  min.segment.length = 0.01, 
                  seed          = labels$seed) 

  } ## End function tmt_labels

##### FUNCTION MAP_CENTER #########################################

map_center <- function(data_points){

## Finds the lat,lon of the center of a set of data points (each a lat,lon).  
    
## Required libraries (sp, raster)

## Data.frame data_points must have variables "lat" and "lon". 

## Transfer the data into a new data.frame
dat <- data.frame(lat=data_points$lat, lon=data_points$lon) 

## Put the coordinates into a SpatialPointDataFrame
coordinates(dat) <- ~lon+lat
proj4string(dat) <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
    
## Get the center point coordinates    
cpt <- coordinates(as(extent(dat), "SpatialPolygons"))

cpt <- as.data.frame(cpt) %>% 
  rename(lat = V2, lon = V1)

cpt <- as.list(cpt)

return(cpt)
}  ## end map_center

##### FUNCTION MAP_ZOOM ###########################################

map_zoom <- function(point_data, center_point){
  
## The data.frame data_points must have variables "lat" and "lon".
## Similarly, center_point must also have a "lon" and "lat".
  
## Set starting conditions.
zoom <- 17
outside <- FALSE

## Look at successively zoomed out levels until all points are inside
for (level in seq(from=zoom, to=5, by=-1)){
  
    ## Get a Google map at a particular zoom level
    t_map <- get_googlemap(center=center_point,
                           zoom=level)
    
    ## Parse out the latitude and longitude data of the bounding box
    box <- attr(t_map,"bb")

    ## Rename the bounding box coordinates
    box <- box %>% 
           rename(left = ll.lon, right = ur.lon, bottom = ll.lat, top = ur.lat)
    
    ## Get the coordinates of the vertices of the box
    box_vertices <- c(box$left,box$bottom,
                      box$left,box$top,
                      box$right,box$top,
                      box$right,box$bottom)
    
    ## Make the vertices into matrix values
    b_v_matrix <- matrix(box_vertices,nrow=4,ncol=2,byrow=TRUE)
    d_p_matrix <- matrix(c(point_data$lon,point_data$lat),
                         nrow=nrow(point_data),
                         ncol=2,
                         byrow=FALSE)
    
    ## Using this function looks like overkill, but it is a general solution to the
    ## problem of finding points inside a polygon. It did not seem to work with negative
    ## values for the longitude. So absolute values are used.
    ## res is a vector of all of the points indicating if they are inside or outside.
    res <- pip2d(abs(b_v_matrix),abs(d_p_matrix))
    
    ## Test if any of the points are outside the bounding box (-1 = outside; 1 = inside)
    if (any(res < 0)){outside <- TRUE}
  
    ## The most zoomed-in level is chosen.
    if(outside != TRUE) {
      level <- level - 1
      return(level)
    
      } ## end if outside
    
  } ## end Level loop

} ## end function map_zoom


```




## Creamsicle Fuel Analysis

```{r data}

## Specify the link
## This is the FULL link
fuel_data <- read_sheet("https://docs.google.com/spreadsheets/d/1b7oFf02cvy1i-9Iao-qJZiANlE8vv8f_4GpgvwAF4TE/edit?usp=sharing")

fuel_data

## The alternative is to specify just the sheet ID. Here,the specific sheet is also specified.
## The result is kinda messy data as there are a lot of lists returned. Here, we just want data.
fuel_info <- read_sheet("1b7oFf02cvy1i-9Iao-qJZiANlE8vv8f_4GpgvwAF4TE", sheet = "Fuel_Log")
fuel_info

## Another try, but with a different function (it uses more of a CSV approach).
## This gives us the values in the spreadsheet. 
## Just what we need (although some chr to number conversions may be required).
fuel_info2 <- range_speedread("1b7oFf02cvy1i-9Iao-qJZiANlE8vv8f_4GpgvwAF4TE", sheet = "Fuel_Log")
fuel_info2


```

## Getting the Locations



```{r locs}

## Use Google Maps to get the general location of each gas station.
## The resolution is just to the city. OK for our purposes.

## Remove any NA rows
clean_fuel <- fuel_info2 %>% 
  drop_na(City)

## Combine the City and State
gas_station <- paste0(clean_fuel$City,", ",clean_fuel$State)

## Count duplicate locations
station_count <- as.data.frame(table(gas_station))

station_count$gas_station <- as.character(station_count$gas_station)

station_count

## Modify the gas_station to include the number of visits if more than 1
station_count <- station_count %>% 
  mutate(station_freq = ifelse(Freq == 1,"",paste0(as.character(Freq),"X"))) %>% 
  mutate(name_count = paste0(gas_station," ",station_freq))


station_count

fuel_locs <- geocode(station_count$gas_station, output="latlon")

map_data <- cbind(station_count,fuel_locs)

map_data

```

## Generate the Map

```{r map}

## Map Center

map_middle <- data.frame(map_center(map_data))

data_points <- map_data %>% 
  dplyr::select(lon, lat)

## Map Zoom
zoom_amount <- map_zoom(point_data   = data_points,
                        center_point = c(map_middle$lon,map_middle$lat))

## Use the map center and the data points (map_data) to make the map

## Rename a column in the data for use with the mapping functions.
point_data <- map_data %>% 
  rename(text = station_freq)

## Retrieve a roadmap map.
temp_map <- get_googlemap(center= map_middle,
                        zoom= zoom_amount,
                        style=no_country, maptype = "roadmap")

## Display the map.
## ggmap(temp_map)

## Plot the labels on the map with ggmap using the custom functions. 
final_map <- ggmap(temp_map) +
   tmt_points(points=point_data,
              points_default=point_default) +
   tmt_labels(point_data) +
   labs(x="",y="") +
   theme(panel.border=element_rect(color="Black", fill=NA, size=2))

final_map

ggsave(filename = "temp/gas_station_map.pdf",final_map,width=8,height=10)

```

