---
title: "Schedule"
subtitle: "Planned and Past Travel"
---

A summary of activities and adventures, past and future.

# *LOOKING AT RECENT AND FORWARD*

*This page is updated as plans develop.*

## 2026

-   February 11-23: San Francisco (I am an American exhibit)
-   March 4-16: Big Island (volcano and bird photography)
-   July 14-20: Big Island (obon and pueo photography)

*No additional trips planned; world is too unsettled*

## 2027

-   October 9-11: Australia (Darwin to Adelaide train)
-   October 24-November 7 (Australia to New Zealand cruise)

# *LOOKING BACK*

## 2026

-   February 11-23: San Francisco (I am an American)
-   March 4-16: Big Island (HVNP, Eruption, Kona Low 1 storm)

## 2025

-   March 19-25: Missouri (Family stuff)
-   May 11-25: Japan (Kyoto)
-   July 9-31: Washington & Oregon
-   July 19-25: Alaska (Nancy cruise), San Juan Islands (Kim), Eugene
-   August 27-September 30: SoCal & Europe (the Netherlands, Denmark, Norway, Sweden)
-   November 22-29: SoCal (Botanical Gardens, Thanksgiving with Myra)

## 2024

-   January 22-30: Southern California (Kimo’s concert, SoCal Botanical Gardens)
-   February 28-March 4: Maui (`i`iwi photography \@ Hosmer Grove)
-   March 13-27: Eugene, Oregon Coast, Kansas City & Portland
-   April 27-May 18: London, Belgium & The Netherlands
-   June 12-July 17: SoCal, Yosemite, Yellowstone, Wisconsin & Chicago
-   September 19-27: SoCal (Botanical Gardens)
-   October 3-23: SoCal to Wisconsin (Visit family; Creamsicle delivery)
-   November 17-December 2: Japan (Aomori, Sendai, Tokyo)
-   December 3-11: Oregon (Eugene & Portland)

## 2023

-   January 11-31: Winter in Japan (SoCal & Japan)
-   March 1-29: 2023 SoCal & Utah in the Spring
-   May 12-16: Big Island (Sokha Graduation)
-   May 31-June 8: SoCal Botanical Gardens
-   August 7-16: Missouri (Tom & MOBOT), West Virginia (Kimo \@ Huntington)
-   September 5-October 2: West Coast & Vancouver Island
-   November 22-December 13: Tokyo & Kyoto (Japan’s Fall Season)

## 2022

-   January 18- February 10: Return from Madison, NikKal Event in SoCal
-   March 16-April 12: Washington, DC (Cherry Blossoms)
-   May 17-June 15: Spring on the West Coast + NYC (brief)
-   September 19-23: Kaua\`i
-   October 26-November 30: West Coast

## 2021

-   March 3-8: Maui
-   June 7-14: Seattle, Bainbridge Island, & Eugene
-   July 23-30: Madison and Kansas City
-   August 24-September 2: Washington DC (Army Museum) & NYC
-   September 21-October 5: Missouri Car Pickup
-   October 14-January 18: Kim to David’s house in Madison

## 2020

-   January 3-4: Kaua\`i (Kim)
-   January 24-28: Tokyo
-   March 6-8: Eugene, Oregon
-   July 3-4: Big Island

## 2019

-   January 3-5: Kim on Kawai\`i
-   January 19-27: Tokyo, Japan
-   February 6-10: Phoenix, AZ
-   March 12-18: Eugene, Oregon
-   April 23-May 5: The Netherlands and Dallas, TX
-   May 29-June 9: SEB in Cincinnati, OH (drive to Wisconsin)
-   July 20-August 1: Seattle + Anchorage & Valdez, Alaska
-   September 19-23: Eugene, Oregon
-   October 7-24: Paris, Bordeaux, San Sebastian & Bilbao
-   November 28-December 2: Southern California
-   December 21-31: Los Angeles & Sydney, Australia
