# Coda

Creating the Gallery Catalog document and the two YouTube videos was a challenge. The entire process involved the use of many AI engines.

## Rapid AI Development

The field of Artificial Intelligence is growing very rapidly. Basic research that shows promising developments is often just a few weeks ahead of improved or new product releases.

Some of the technology used here has already been replaced with much better versions. These range from the basic inference software that interprets and summarizes the data to the graphics engines that create still and video elements.

It is very likely this document will not age well. Soon, the features shown here will be very commonplace or replaced by much more sophisticated alternatives.

What's here is a freezing of a moment in time. It's a demonstration of what an average person can do in this general arena of art, at the start of 2025.

## AI Cooperation

Working with the AI engines, particularly those which produced text, was an interesting experience.

The dialogues shown in the previous chapters have an almost aggressive enthusiasm. Note how the exchanges usually end with a question that begins "Do you want me to ..." or something that's equivalent.

There are lots of courteous remarks, such as "Thank you ...".

All of this makes it interesting to work with the AI engines as though you're in a partnership. It's easy to forget that it isn't a human on the other end of the conversation.

## Was the Project Successful?

The primary product was the Gallery Catalog. Quite a few people saw the web-based presentation of the catalog before the critique podcasts were produced. The general impression was that the images were good art. In that sense, I believe the project was successful.

The podcasts, as YouTube videos, are a recent addition and few people have seen them.
